drop table APPLY;
drop sequence APPLY_SEQ;

CREATE TABLE APPLY(					
AP_INDEX NUMBER NOT NULL PRIMARY KEY, -- 신청 No
AP_ID VARCHAR2(40) NOT NULL ,	-- 신청인 아이디
AP_RDATE TIMESTAMP NOT NULL,	-- 신청한 날짜
AP_CINDEX NUMBER NOT NULL,		-- 신청한 클래스 No
AP_TITLE VARCHAR2(100) NOT NULL,-- 클래스 이름
AP_LOCATE VARCHAR2(100) NOT NULL,-- 클래스 장소
AP_CDATE DATE NOT NULL,			-- 클래스 날짜
AP_PROG NUMBER default 1,		-- 신청 상태 (1: 가신청, 2: 입금완료(신청완료), 0:취소)
 CONSTRAINT FK_APPLY_ID FOREIGN KEY(AP_ID) REFERENCES USER_TABLE(USER_ID),
 CONSTRAINT FK_APPLY_INDEX FOREIGN KEY(AP_CINDEX) REFERENCES ONEDAY(ONE_INDEX)
);

CREATE SEQUENCE APPLY_SEQ;


select * from APPLY;
delete from APPLY;

update apply
set ap_prog = '0'
where ap_id = 'hansol11' and ap_cindex = '5'
	
	