drop table APPLY;
drop sequence APPLY_SEQ;

CREATE TABLE APPLY(					
AP_INDEX NUMBER NOT NULL PRIMARY KEY,
AP_ID VARCHAR2(40) NOT NULL ,
AP_RDATE TIMESTAMP NOT NULL,
AP_CINDEX NUMBER NOT NULL,
AP_TITLE VARCHAR2(100) NOT NULL,
AP_LOCATE VARCHAR2(100) NOT NULL,
AP_CDATE DATE NOT NULL,
AP_PROG NUMBER default 1,
 CONSTRAINT FK_APPLY_ID FOREIGN KEY(AP_ID) REFERENCES USER_TABLE(USER_ID),
 CONSTRAINT FK_APPLY_INDEX FOREIGN KEY(AP_CINDEX) REFERENCES ONEDAY(ONE_INDEX)
);

CREATE SEQUENCE APPLY_SEQ;


select * from APPLY;
delete from APPLY;


	
	