drop table ONEDAY;
drop sequence ONEDAY_SEQ;

CREATE TABLE ONEDAY(					
ONE_INDEX NUMBER NOT NULL,	
ONE_TITLE VARCHAR2(100)NOT NULL,
ONE_LINE VARCHAR2(100) NOT NULL,
WRITER_ID VARCHAR2(40) NOT NULL,				
ONE_CONTENT CLOB NOT NULL,
ONE_SEAT NUMBER NOT NULL,
ONE_ACTUAL_SEAT NUMBER default 0,
ONE_PRICE NUMBER NOT NULL,
SAVEFILE VARCHAR2(50),					
ORIGINALFILE VARCHAR2(50),
ONE_READCOUNT NUMBER,	
ONE_RDATE DATE NOT NULL,
ONE_PODATE TIMESTAMP NOT NULL,									
ONE_TYPE VARCHAR2(40) NOT NULL,
ONE_LOCATE VARCHAR2(50) NOT NULL,
PRIMARY KEY(ONE_INDEX)
);

CREATE SEQUENCE ONEDAY_SEQ;

select * from ONEDAY;


CREATE TABLE QNABOARD(
QNA_INDEX NUMBER NOT NULL,	-- 게시판 번호
QNA_TITLE VARCHAR2(100)NOT NULL, -- 게시판 제목
QNA_WRITER VARCHAR2(40) NOT NULL, -- 게시판 글쓴이
QNA_DATE TIMESTAMP NOT NULL, -- 게시판 작성 날짜
QNA_SAVEFILE VARCHAR2(50), -- DB에 저장될 사진
QNA_ORIGINALFILE VARCHAR2(50)	 -- 		
)

select r.*
from (select ROWNUM RNUM, o.*
			from ONEDAY o
			where ONE_RDATE >= sysdate) r
where RNUM <= 3
			
