delete from QNA;
DROP TABLE QNA;
DROP SEQUENCE QNA_SEQ;


CREATE TABLE QNA(
QNA_NUM NUMBER PRIMARY KEY,
QNA_ID VARCHAR2(40), 
QNA_EXID VARCHAR2(40), 
QNA_TITLE VARCHAR2(300),
QNA_CONTENT CLOB,
QNA_PASS VARCHAR2(30),
QNA_SEQURE VARCHAR2(30),
QNA_RE_REF NUMBER ,
QNA_RE_LEV NUMBER ,
QNA_RE_SEQ NUMBER,
QNA_DATE date,
QNA_READCOUNT NUMBER
--CONSTRAINT FK_EXID FOREIGN KEY(QNA_EXID) REFERENCES EXPERT_TABLE(EXPERT_ID)
);

CREATE SEQUENCE QNA_SEQ;

select * from QNA;
