CREATE TABLE QNABOARD(
QNA_INDEX NUMBER NOT NULL,   
QNA_TITLE VARCHAR2(100)NOT NULL,
QNA_WRITER VARCHAR2(40) NOT NULL,
ONE_CONTENT CLOB NOT NULL,
QNA_DATE TIMESTAMP NOT NULL,
QNA_SAVEFILE VARCHAR2(50),
QNA_ORIGINALFILE VARCHAR2(50)         
);
