--신고 (회원→전문가)
DROP TABLE REPORTEX;
CREATE TABLE REPORTEX(
REPEX_INDEX NUMBER NOT NULL PRIMARY KEY,         --신고 글 번호
REPEX_EXID VARCHAR2(40) NOT NULL,            --신고 전문가 아이디
REPEX_UID VARCHAR2(40) NOT NULL,               --신고하는 일반 회원 아이디
REPEX_DATE TIMESTAMP NOT NULL,               --신고 날짜
REPEX_CATE VARCHAR2(300) NOT NULL,            --신고 사유 1(대분류)
REPEX_DES CLOB NOT NULL,                  --신고 상세 사유   
REPEX_TIMES NUMBER NOT NULL,               --신고 누적 횟수
REPEX_STATE NUMBER NOT NULL,               --조치 전/후 전문가 회원 상태
CONSTRAINT REPEX_EXID FOREIGN KEY(REPEX_EXID) REFERENCES EXPERT_TABLE(EXPERT_ID),
CONSTRAINT REPEX_UID FOREIGN KEY(REPEX_UID) REFERENCES USER_TABLE(USER_ID)
);

SELECT * FROM REPORTEX;

DROP SEQUENCE REX_SEQ;
CREATE SEQUENCE REX_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE;

INSERT INTO REPORTEX
VALUES(REX_SEQ.NEXTVAL, 'user5678', 'user1234', sysdate, '기타', '웅애웅앵 테스트~', 1, 0);

--신고 (전문가→회원)
DROP TABLE REPU;
CREATE TABLE REPU(                  
REPU_INDEX NUMBER NOT NULL PRIMARY KEY,            --신고 글 번호
REPU_UID VARCHAR2(40) NOT NULL,               --신고 회원 아이디
REPU_EXID VARCHAR2(40) NOT NULL,               --신고하는 전문가 회원 아이디
REPU_DATE TIMESTAMP NOT NULL,               --신고 날짜
REPU_CATE VARCHAR2(300) NOT NULL,            --신고 사유(대분류)
REPU_DES CLOB NOT NULL,                  --신고 상세 사유
REPU_TIMES NUMBER NOT NULL,               --신고 누적 횟수
REPU_STATE NUMBER NOT NULL,               --조치 전/후 전문가 회원 상태
CONSTRAINT REPU_UID FOREIGN KEY(REPU_UID) REFERENCES USER_TABLE(USER_ID),
CONSTRAINT REPU_EXID FOREIGN KEY(REPU_EXID) REFERENCES EXPERT_TABLE(EXPERT_ID)
);

DROP SEQUENCE REU_SEQ;
CREATE SEQUENCE REU_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE;

INSERT INTO REPU
VALUES(REU_SEQ.NEXTVAL, 'user1234', 'user5678', sysdate, '기타', '웅앵 테스트~', 1,0);

SELECT EX.EXPERT_ID, REX.REPEX_EXID, REX.REPEX_TIMES
FROM EXPERT_TABLE EX, REPORTEX REX
WHERE EX.EXPERT_ID = REX.REPEX_EXID
ORDER BY REX.REPEX_EXID;