CREATE TABLE "EEUM"."REQUEST_FILE" 
   (	"FILE_NO" NUMBER NOT NULL ENABLE, 
	"REQUEST_NO" NUMBER, 
	"FILE_NAME" VARCHAR2(40), 
	"FILE_ORIGINAL" VARCHAR2(100), 
	"FILE_THUMB_NAME" VARCHAR2(100), 
	"REQUEST_FILE_DATE" DATE, 
	 PRIMARY KEY ("FILE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  select count(*) from REQUEST where expert_id = 'aaa';
  
  CREATE TABLE "EEUM"."REQUEST" 
   (	"REQUEST_NO" NUMBER NOT NULL ENABLE, 
	"EXPERT_ID" VARCHAR2(40) NOT NULL, 
	"WRITER" VARCHAR2(40), 
	"WRITER_TYPE" VARCHAR2(40), 
	"BUILDING_TYPE" VARCHAR2(40), 
	"BUILDING_TEXT" VARCHAR2(2000), 
	"REPAIR_TYPE" VARCHAR2(40), 
	"REPAIR_TEXT" VARCHAR2(2000), 
	"SIMPLE_REQ_TEXT" VARCHAR2(2000), 
	"REQUEST_DATE" DATE, 
	 PRIMARY KEY ("REQUEST_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  create sequence request_seq;
  create sequence request_file_seq;
  
  SELECT R.EXPERT_ID, R.WRITER, E.EXPERT_NAME, P.PF_GRADE, P.PF_CATE, P.PF_SAVEPROFILE
  FROM REQUEST R INNER JOIN
  			EXPERT_TABLE E ON R.EXPERT_ID = E.EXPERT_ID LEFT OUTER join
  			PORTFOLIO P ON R.EXPERT_ID = P.PF_EXID
  WHERE R.WRITER = 'admin' AND R.EXPERT_ID = 'hansol00'
  ORDER BY R.REQUEST_DATE DESC