CREATE TABLE RESERVATION (
RS_EXID VARCHAR2(40) NOT NULL,					-- 예약된 전문가 
RS_UID VARCHAR2(40) NOT NULL,					-- 예약한 사용자
RS_DATE VARCHAR2(100),				-- 예약 날짜
RS_TIME VARCHAR2(40),					-- 예약 시간
RS_MONEY VARCHAR2(100),			-- 예상 가격 
RS_STATE NUMBER DEFAULT 0,		-- 예약 상태 (0: 예약 신청, 1: 예약 확정; 2:서비스 완료; 3:취소)
CONSTRAINT FK_RS_EXID FOREIGN KEY(RS_EXID) REFERENCES EXPERT_TABLE(EXPERT_ID),
CONSTRAINT FK_RS_UID FOREIGN KEY(RS_UID) REFERENCES USER_TABLE(USER_ID)
);

select * from reservation
delete reservation

SELECT E.EXPERT_ID, E.EXPERT_NAME, P.PF_GRADE, P.PF_CATE, P.PF_SAVEPROFILE
FROM PORTFOLIO P, EXPERT_TABLE E
WHERE E.EXPERT_ID = P.PF_EXID