--후기 글을(통계데이터 제외) 생성하는 테이블
drop table REVIEW_BOARD;
create table REVIEW_BOARD(
	RV_INDEX NUMBER NOT NULL PRIMARY KEY,		--후기 글 번호
	RV_UID VARCHAR2(40) NOT NULL,											--후기 작성자 ID
	RV_EXID VARCHAR2(40) NOT NULL,										--후기 전문가 ID
	RV_TITLE VARCHAR2(100) NOT NULL,								--후기 글 제목
	RV_CON CLOB NOT NULL,																	--후기 상세 내용
	RV_STAR NUMBER(3,2) NOT NULL											--후기 별점
);

ALTER TABLE REVIEW_BOARD
ADD CONSTRAINT RV_UID FOREIGN KEY(RV_UID)
REFERENCES USER_TABLE(USER_ID);

ALTER TABLE REVIEW_BOARD
ADD CONSTRAINT RV_EXID FOREIGN KEY(RV_EXID)
REFERENCES EXPERT_TABLE(EXPERT_ID);

CREATE SEQUENCE RV_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

select * from REVIEW_BOARD;

SELECT * FROM expert_table
UNION    
SELECT * FROM PORTFOLIO;

SELECT * FROM EXPERT_TABLE,PORTFOLIO;


INSERT INTO REVIEW_BOARD
VALUES(RV_SEQ.NEXTVAL, 'user1234', 'user5678', '후기 테스트', '웅앵웅앵웅앵', 3.75);