CREATE TABLE USER_TABLE (
USER_PROFILE VARCHAR2(4000) NOT NULL,
USER_JUMIN1 VARCHAR2(13) NOT NULL,
USER_JUMIN2 VARCHAR2(13) NOT NULL,
USER_NAME VARCHAR2(50) NOT NULL,
USER_NICK VARCHAR2(50) NOT NULL,
USER_ID VARCHAR2(40) PRIMARY KEY NOT NULL,
USER_PASS VARCHAR2(100) NOT NULL,
USER_ADDR1 VARCHAR2(300) NOT NULL,
USER_ADDR2 VARCHAR2(300) NOT NULL,
USER_PHONE1 VARCHAR2(3) NOT NULL,
USER_PHONE2 VARCHAR2(4) NOT NULL,
USER_PHONE3 VARCHAR2(4) NOT NULL,
USER_EMAIL1 VARCHAR2(50) NOT NULL,
USER_EMAIL2 VARCHAR2(50) NOT NULL
);

select * from USER_TABLE
