CREATE TABLE USER_TABLE (
USER_PROFILE VARCHAR2(4000) NOT NULL,
USER_SAVEPROFILE VARCHAR2(4000) NOT NULL,
USER_JUMIN1 VARCHAR2(10) NOT NULL,
USER_JUMIN2 VARCHAR2(60) NOT NULL,
USER_NAME VARCHAR2(50) NOT NULL,
USER_NICK VARCHAR2(50) NOT NULL,
USER_ID VARCHAR2(40) PRIMARY KEY NOT NULL,
USER_PASS VARCHAR2(100) NOT NULL,
USER_ADDR1 VARCHAR2(10) NOT NULL,
USER_ADDR2 VARCHAR2(300) NOT NULL,
USER_ADDR3 VARCHAR2(300) NOT NULL,
USER_PHONE1 VARCHAR2(3) NOT NULL,
USER_PHONE2 VARCHAR2(4) NOT NULL,
USER_PHONE3 VARCHAR2(4) NOT NULL,
USER_EMAIL1 VARCHAR2(50) NOT NULL,
USER_EMAIL2 VARCHAR2(50) NOT NULL
)

select * from USER_TABLE
delete user_table
where user_id = 'hansol3021'
alter table USER_TABLE modify(USER_SAVEPROFILE varchar2(4000))
drop table user_table